WebProjectAzure/Models/AbonnementModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebProjectAzure.Models
{
    /// <summary>
    /// Classe de l'abonnement 
    /// </summary>
    public class AbonnementModel
    {
        /// <summary>
        /// Id de l'abonnement
        /// </summary>
        [Required]
        [Key]
        public int Id { get; set; }


        /// <summary>
        /// Date de début de l'abonnement
        /// </summary>
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DateDebut { get; set; }

        /// <summary>
        /// Duree de l'abonnement
        /// </summary>
        [Required]
        [Range(1, 12)]
        [DisplayName("Duree")]
        public int Duree { get; set; }

        /// <summary>
        /// Tarif mensuel de l'abonnement
        /// </summary>
        [Required]
        [DisplayName("Tarif Mensuel")]
        [DataType(DataType.Currency)]
        public double TarifMensuel { get; set; }

        /// <summary>
        /// Mail de l'utilisateur
        /// </summary>
        [Required]
        [DisplayName("Mail")]
        public string Mail { get; set; }

        /// <summary>
        /// Identifiant Azure de la VM
        /// </summary>
        public string IdVm { get; set; }
    }
}

WebProjectAzure/Models/ErrorViewModel.cs
namespace WebProjectAzure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebProjectAzure/Controllers/AbonnementModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProjectAzure.Data;
using WebProjectAzure.Models;
using WebProjectAzure.Azure;
using Microsoft.Azure.Management.Compute.Fluent;

namespace WebProjectAzure.Controllers
{
    public class AbonnementModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AbonnementModelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AbonnementModels
        public async Task<IActionResult> Index(string sortOrder)
        {
            if (_context.ListeAbonnement == null) return Problem("Entity set 'ApplicationDbContext.abonnements'  is null.");

            if (!_context.ListeAbonnement.Any()) return RedirectToAction(nameof(Create));

            return View(await _context.ListeAbonnement
                .Where(a => a.Mail == HttpContext.User.Identity.Name)
                .ToListAsync());
        }

        // GET: AbonnementModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ListeAbonnement == null)
            {
                return NotFound();
            }

            var abonnementModel = await _context.ListeAbonnement
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abonnementModel == null)
            {
                return NotFound();
            }

            return View(abonnementModel);
        }

        // GET: AbonnementModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AbonnementModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateDebut,Duree,TarifMensuel,Mail")] AbonnementModel abonnementModel)
        {
            IVirtualMachine? vm = AzureManager.Instance.CreateVM(abonnementModel);

            abonnementModel.Mail = HttpContext.User.Identity.Name;
            abonnementModel.IdVm = vm.Id;

            _context.Add(abonnementModel);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: AbonnementModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ListeAbonnement == null)
            {
                return NotFound();
            }

            var abonnementModel = await _context.ListeAbonnement.FindAsync(id);
            if (abonnementModel == null)
            {
                return NotFound();
            }
            return View(abonnementModel);
        }

        // POST: AbonnementModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateDebut,Duree,TarifMensuel,Mail")] AbonnementModel abonnementModel)
        {
            if (id != abonnementModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(abonnementModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbonnementModelExists(abonnementModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(abonnementModel);
        }

        // GET: AbonnementModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ListeAbonnement == null)
            {
                return NotFound();
            }

            var abonnementModel = await _context.ListeAbonnement
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abonnementModel == null)
            {
                return NotFound();
            }

            return View(abonnementModel);
        }

        // POST: AbonnementModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ListeAbonnement == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ListeAbonnement'  is null.");
            }
            var abonnementModel = await _context.ListeAbonnement.FindAsync(id);
            if (abonnementModel != null)
            {
                _context.ListeAbonnement.Remove(abonnementModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbonnementModelExists(int id)
        {
            return (_context.ListeAbonnement?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebProjectAzure/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebProjectAzure.Models;

namespace WebProjectAzure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Abonnements()
        {
            return View("./Views/AbonnementModels/Index.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebProjectAzure/Views/AbonnementModels/Create.cshtml
@model WebProjectAzure.Models.AbonnementModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AbonnementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control" />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duree" class="control-label"></label>
                <input asp-for="Duree" class="form-control" />
                <span asp-validation-for="Duree" class="text-danger"></span>
            </div>
            <!--<div class="form-group">
                <label asp-for="TarifMensuel" class="control-label"></label>
                <input asp-for="TarifMensuel" class="form-control" />
                <span asp-validation-for="TarifMensuel" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="TarifMensuel" class="control-label"></label>
                <select class="form-control" id="TarifMensuel" name="TarifMensuel">
                    <option>10</option> 
                    <option>20</option> 
                    <option>30</option> 
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProjectAzure/Views/AbonnementModels/Delete.cshtml
@model WebProjectAzure.Models.AbonnementModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AbonnementModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifMensuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifMensuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebProjectAzure/Views/AbonnementModels/Details.cshtml
@model WebProjectAzure.Models.AbonnementModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AbonnementModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TarifMensuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TarifMensuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebProjectAzure/Views/AbonnementModels/Edit.cshtml
@model WebProjectAzure.Models.AbonnementModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AbonnementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control" />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duree" class="control-label"></label>
                <input asp-for="Duree" class="form-control" />
                <span asp-validation-for="Duree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TarifMensuel" class="control-label"></label>
                <input asp-for="TarifMensuel" class="form-control" />
                <span asp-validation-for="TarifMensuel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProjectAzure/Views/AbonnementModels/Index.cshtml
@model IEnumerable<WebProjectAzure.Models.AbonnementModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    @*<button type="button" asp-action="Create" class="btn btn-primary">Create New</button>*@
       <a asp-action="Create">Create New</a> 
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateDebut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TarifMensuel)
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["MailSortParm"]">@Html.DisplayNameFor(model => model.Mail)</a>
            </th>
            <th>
                Subscription Action
            </th>
            <th>
                Virtual Machine Status
            </th>
            <th>
                Virtual Machine Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateDebut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TarifMensuel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mail)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
                <td>
                    idVm
                    @*@Html.DisplayFor(modelItem =>item.IdVm)*@
                </td>
                <td>
                    <a asp-action="Start" asp-route-id="@item.Id">Start</a> |
                    @*<form class="form-inline" asp-area="" asp-page="" asp-route-returnUrl="@Url.Action()">
                <button type="submit" class="btn btn-success">Start</button>
                </form>*@
                    @*<button asp-action="Start" class="btn btn-success">Start</button>
                @*<button type="button" asp-action="Start" class="btn btn-success">Start</button>*@
                    <a asp-action="Stop" asp-route-id="@item.Id">Stop</a>
                    @*<button type="button" asp-action="Stop" class="btn btn-danger">Stop</button>*@
                </td>
            </tr>
        }
    </tbody>
</table>

WebProjectAzure/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center container">
    <h1 class="display-4 my-4">Welcome to Sup de Vinci Gaming</h1>

    <div id="carouselExampleCaptions" class="carousel slide mx-5" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Elden Ring"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Borderlands"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="7 Days to die"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Dofus Retro"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Minecraft Dungeons"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Rocket League"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/EldenRing.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Borderlands.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/7DaysToDie.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Dofus.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/MinecraftDungeons.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/RocketLeague.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

WebProjectAzure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - jeu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/jeu.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid mx-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="../../../../sdvGaming.png" width="45" height="45" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AbonnementModels" asp-action="Index">Abonnements</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - jeu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>